/** Fonts loaded in index.html and offered in the poster text picker. */
export const FONTS = [
  "Alfa Slab One",
  "Archivo Black",
  "Architects Daughter",
  "Caveat",
  "Cinzel",
  "Cormorant Garamond",
  "Fredoka",
  "IBM Plex Mono",
  "IM Fell English",
  "Inter",
  "Josefin Sans",
  "Libre Baskerville",
  "Monoton",
  "Old Standard TT",
  "Permanent Marker",
  "Poiret One",
  "Press Start 2P",
  "PT Mono",
  "Roboto",
  "Russo One",
  "Share Tech Mono",
  "Shippori Mincho",
  "Space Grotesk",
] as const;
